spring:
  cloud:
    stream:
      bindings:
        process-in-0.destination: process-objects
        process-out-0.destination: process-matched-patterns
      kafka:
        streams:
          binder:
            applicationId: kafka-feed-example
            brokers: localhost:9092
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde